openapi: 3.0.2
info:
  title: api
  version: 1.0.0
  description: API Definitions.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Swagger API Team
    url: 'http://swagger.io'
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /user:
    summary: Returns the authenticated user.
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Success
components:
  schemas:
    User:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
