openapi: 3.0.2
info:
  title: api
  version: 1.0.0
  description: API Definitions.
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Swagger API Team
    url: 'http://swagger.io'
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /user:
    summary: Returns the authenticated user.
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: Success
  '/weather/{city}':
    description: ''
    get:
      parameters:
        -
          name: city
          schema:
            $ref: '#/components/schemas/City'
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Weather'
          description: Sucessfully get weather information for specified city.
      description: Get `Weather` for a specific `City`
components:
  schemas:
    User:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
    Weather:
      description: ''
      type: object
      properties:
        description:
          description: ''
          type: string
        windSpeed:
          format: double
          description: ''
          type: number
        temperature:
          format: double
          description: ''
          type: number
        feelsLike:
          format: double
          description: ''
          type: number
        location:
          description: ''
          type: string
    City:
      description: List of cities
      enum:
        - LOS_ANGELES
        - SAN_DIEGO
        - HUNTINGTON_BEACH
        - SAN_FRANCISCO
      type: string
